Pr99 100
AdamScoggins/pet-overload pull request #101
Opened 2023-04-14 19:13 UTC by Iris06-cs

fixed conflicts, didn't properly comment out un-needed code

2023-04-14 19:14 UTC, Lvcky-gg approved these changes

2023-04-14 19:46 UTC, Lvcky-gg requested changes
send files to db as is. return from db as html strings to parse on frontend
eg. <p>details</p> is now <div>parse(details)</div>

2023-04-14 20:37 UTC, AdamScoggins approved these changes

2023-04-14 20:57 UTC, Lvcky-gg approved these changes
this works

2023-04-15 16:10 UTC, philling83 approved these changes
LGTM

2023-04-15 16:17 UTC, merged